services:

  mysql:
    image: mysql
    container_name: kickstart-templete_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    networks:
      - network
    restart: unless-stopped
    tty: true

  node:
    depends_on:
      - mysql
    image: node
    container_name: kickstart-templete_node
    ports:
      - 80:80
      - 8080:8080
      - 3000:3000
      - 4000:4000
      - 4321:4321
      - 443:443
    networks:
      - network
    volumes:
      - ./:/home/node
    working_dir: /home/node/
    restart: unless-stopped
    tty: true

networks:
  network:
    driver: bridge
