import colors from "tailwindcss/colors";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue,css}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Atkinson"],
      },
      colors: {
        transparent: colors.transparent,
        current: colors.current,
        bg_light: colors.white,
        bg_dark: colors.black,
        tx_light: colors.black,
        tx_dark: colors.white,
        black: colors.black,
        white: colors.white,
        gray: colors.gray,
        primary: colors.indigo,
        secondary: colors.teal,
        success: colors.green,
        danger: colors.red,
        warning: colors.yellow,
        info: colors.sky,
        red: colors.red,
        green: colors.green,
        blue: colors.blue,
        cyan: colors.cyan,
        magenta: colors.pink,
        yellow: colors.yellow,
        orange: colors.orange,
        pink: colors.pink,
        purple: colors.purple,
      },
      typography: ({ theme }) => ({
        red: {
          css: {
            "--tw-prose-body": theme("colors.red[800]"),
            "--tw-prose-headings": theme("colors.red[900]"),
            "--tw-prose-lead": theme("colors.red[700]"),
            "--tw-prose-links": theme("colors.red[900]"),
            "--tw-prose-bold": theme("colors.red[900]"),
            "--tw-prose-counters": theme("colors.red[600]"),
            "--tw-prose-bullets": theme("colors.red[400]"),
            "--tw-prose-hr": theme("colors.red[300]"),
            "--tw-prose-quotes": theme("colors.red[900]"),
            "--tw-prose-quote-borders": theme("colors.red[300]"),
            "--tw-prose-captions": theme("colors.red[700]"),
            "--tw-prose-code": theme("colors.red[900]"),
            "--tw-prose-pre-code": theme("colors.red[100]"),
            "--tw-prose-pre-bg": theme("colors.red[900]"),
            "--tw-prose-th-borders": theme("colors.red[300]"),
            "--tw-prose-td-borders": theme("colors.red[200]"),
            "--tw-prose-invert-body": theme("colors.red[200]"),
            "--tw-prose-invert-headings": theme("colors.white"),
            "--tw-prose-invert-lead": theme("colors.red[300]"),
            "--tw-prose-invert-links": theme("colors.white"),
            "--tw-prose-invert-bold": theme("colors.white"),
            "--tw-prose-invert-counters": theme("colors.red[400]"),
            "--tw-prose-invert-bullets": theme("colors.red[600]"),
            "--tw-prose-invert-hr": theme("colors.red[700]"),
            "--tw-prose-invert-quotes": theme("colors.red[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.red[700]"),
            "--tw-prose-invert-captions": theme("colors.red[400]"),
            "--tw-prose-invert-code": theme("colors.white"),
            "--tw-prose-invert-pre-code": theme("colors.red[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.red[600]"),
            "--tw-prose-invert-td-borders": theme("colors.red[700]"),
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
