import {
  capitalizeFirstString,
  getEgbAge,
  type GetEgbAgeType,
  getEgbYear,
  getFormattedDate,
  getLangI18n,
  getSwitchI18n,
  getUrlI18n,
  getYear,
  pastYears,
  randomArray,
  translateI18n,
  typeHello,
} from "./ts";

import {
  ColorsFooterLayout,
  ColorsNav,
  DefaultA,
  DefaultEmail,
  developsCollection,
  issuesCollection,
  milestonesCollection,
  postsCollection,
  DefaultHeadLayout,
} from "./astro";

import {
  DefaultTsxA,
  type DefaultTsxAType,
  DefaultTsxEmail,
  type DefaultTsxEmailType,
  ReactHello,
} from "./tsx";

export {
  capitalizeFirstString,
  ColorsFooterLayout,
  ColorsNav,
  DefaultA,
  DefaultEmail,
  DefaultHeadLayout,
  DefaultTsxA,
  type DefaultTsxAType,
  DefaultTsxEmail,
  type DefaultTsxEmailType,
  developsCollection,
  getEgbAge,
  type GetEgbAgeType,
  getEgbYear,
  getFormattedDate,
  getLangI18n,
  getSwitchI18n,
  getUrlI18n,
  getYear,
  issuesCollection,
  milestonesCollection,
  pastYears,
  postsCollection,
  randomArray,
  ReactHello,
  translateI18n,
  typeHello,
};
